name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest  
  
    steps:
      - uses: actions/checkout@v2  
        with:
          fetch-depth: 0  
  
      - name: Install PHP and extensions
        uses: shivammathur/setup-php@v2  
        with:
          php-version: '7.4'
          extensions: mysqli

  
  
  deploy:
 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: HRKU-0a0a621b-738e-4966-99fe-ac1fc231aac3
          heroku_app_name: registro
          heroku_email: karenchicaiza989@gmail.com
          healthcheck: "https://registro-ada30281513a.herokuapp.com/"
          rollbackonhealthcheckfailed: true